name: Generate Custom Profile Card

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  push:
    branches:
      - main
    paths:
      - 'neofetch.json'
      - 'new_pfp.jpg'
      - 'generate_card.py'
      - 'requirements.txt'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Card
        run: python generate_card.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add profile-card.svg
          git commit -m "docs: dynamically update profile card" || exit 0
          git push
